<?php

declare(strict_types=1);

namespace App\Domain\Seller\Enums;

/**
 * Why an upload was blocked at the door (P5-1). The customer-facing message
 * is OURS, fixed per category — never text generated by the model, because
 * a document can contain text written to manipulate the AI (prompt
 * injection) and we must never echo that back as if it were our message.
 */
enum DocumentRejectionCategory: string
{
    case EXPLICIT = 'explicit';
    case WRONG_DOCUMENT = 'wrong_document';
    case UNREADABLE = 'unreadable';

    public function customerMessage(SellerDocumentType $type): string
    {
        return match ($this) {
            self::EXPLICIT => 'This file was rejected because it contains inappropriate content.',
            self::WRONG_DOCUMENT => "This does not look like a {$type->label()}. Please upload the correct document.",
            self::UNREADABLE => "The {$type->label()} is not clear enough to read. Please upload a sharper, uncropped photo or scan.",
        };
    }
}
